apiVersion: v1
kind: ConfigMap
metadata:
  name: dumall-config
  namespace: dumall
data:
  # 数据库配置
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "dumall"
  DB_USER: "dumall_user"
  
  # Redis配置
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # 应用配置
  API_GATEWAY_URL: "http://nginx-gateway-service"
  FRONTEND_URL: "http://frontend-service:5174"
  
  # 日志配置
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "JSON" 