apiVersion: v1
kind: Secret
metadata:
  name: dumall-secrets
  namespace: dumall
type: Opaque
data:
  # 数据库密码 (base64编码)
  DB_PASSWORD: ZHVtYWxsX3Bhc3N3b3Jk
  # Redis密码 (base64编码)
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
  # JWT密钥 (base64编码)
  JWT_SECRET: ZHVtYWxsLWp3dC1zZWNyZXQta2V5
  # API密钥 (base64编码)
  API_KEY: ZHVtYWxsLWFwaS1rZXk= 