# 前端应用
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dumall
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hackwoman/dumall-frontend:latest
        ports:
        - containerPort: 5174
        env:
        - name: VITE_API_BASE_URL
          value: "http://nginx-gateway-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 5174
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 5174
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dumall
spec:
  selector:
    app: frontend
  ports:
  - port: 5174
    targetPort: 5174
  type: ClusterIP
---
# Nginx API网关
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: dumall
  labels:
    app: nginx-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
      - name: nginx-gateway
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-service
  namespace: dumall
spec:
  selector:
    app: nginx-gateway
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
# Nginx配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dumall
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      upstream user-service {
        server user-service:8081;
      }
      
      upstream product-service {
        server product-service:8082;
      }
      
      upstream payment-service {
        server payment-service:8083;
      }
      
      upstream inventory-service {
        server inventory-service:8084;
      }
      
      upstream frontend-service {
        server frontend-service:5174;
      }
      
      server {
        listen 80;
        
        # 健康检查
        location /health {
          return 200 "healthy\n";
          add_header Content-Type text/plain;
        }
        
        # 前端应用
        location / {
          proxy_pass http://frontend-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # API路由
        location /api/users {
          proxy_pass http://user-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/products {
          proxy_pass http://product-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/payments {
          proxy_pass http://payment-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api/inventory {
          proxy_pass http://inventory-service;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
# 外部访问入口
apiVersion: v1
kind: Service
metadata:
  name: dumall-ingress
  namespace: dumall
spec:
  selector:
    app: nginx-gateway
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer 